/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package my_first_plugin;

import org.junit.jupiter.api.Test;

import be.seeseemelk.mockbukkit.MockBukkit;
import be.seeseemelk.mockbukkit.ServerMock;
import be.seeseemelk.mockbukkit.entity.PlayerMock;
import net.kyori.adventure.text.TextComponent;

import static org.assertj.core.api.Assertions.assertThat;

import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.inventory.ItemStack;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;

class MyExamplePluginTest {
  private ServerMock server;

  @SuppressWarnings("unused")
  private MyExamplePlugin myPlugin;

  @BeforeEach
  void setup() {
    this.server = MockBukkit.mock();
    this.myPlugin = MockBukkit.load(MyExamplePlugin.class);
  }

  @AfterEach
  void teardown() {
    MockBukkit.unmock();
  }

  @Test
  void Player_ShouldRecieve_AnItem_WhenThey_LogIn() {
    final PlayerMock player = server.addPlayer();

    server.getPluginManager().assertEventFired(PlayerJoinEvent.class);

    final ItemStack hammer = player.getInventory().getItem(0);
    final TextComponent displayName = (TextComponent) hammer.getItemMeta()
        .displayName();
    assertThat(displayName.content()).isEqualTo("Stone Hammer");
  }

  @SuppressWarnings("unused")
  @Test
  void Tests_Should_Be_Able_To_Reference_NMS() {
    final net.minecraft.world.item.ItemStack nmsStack = null;
  }
}
